spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: d000000
  thymeleaf:
    cache: false



  level:
    root: info
    com.lxd: debug
  file:
    name: log/blog-dev.log

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png